### ISSUE TITLE
More versatile filtering methods

### ISSUE THREAD

**Issue by hope-data-science** [MagicHead99/bread#1]
I can find that the function could filter using regular expression. Is there a way to filter numbers according to their range?

Thanks.

**Comment by MagicHead99** [comment]
Filtering by range would indeed be very useful. Thanks for the suggestion.

There is a way with grep if you can figure out the string pattern, but it will be a very complex regex unless your values are something integers between 1 and 100.

It's a lot easier with awk. I pushed a new version on the develop branch that contains a new "bnumrange" function. The functionalities were also added to the bread() all-in-one function. It was tested very little and uploading it to cran might take a bit.

**Comment by MagicHead99** [comment]
Now on main and on it's way to cran
