### ISSUE TITLE
Remove dependencies

### ISSUE THREAD

**Issue by nathaneastwood** [MagicHead99/bread#5]
Hi, first of all, this is a nice package, kudos.

You might want to consider removing `dplyr` from the package. It seems you mostly import it for the pipe (`%>%`) and `filter()`. However since the package is already based around `data.table`, why not use that for the filtering (which potentially will work faster too). I would argue that it is not best practice to use the pipe within a package and it's better to separate out your steps for debugging purposes, e.g.

```r
a <- fn(...)
a <- b(a)

# or even
a <- b(fn(...))

# instead of
a <- fn(...) %>% b()
```

Also, from the [R Packages book](https://r-pkgs.org/dependencies.html#other-dependencies):

> `Depends`: Prior to the roll-out of namespaces in R 2.14.0 in 2011, `Depends` was the only way to "depend" on another package. Now, despite the name, you should almost always use `Imports`, not `Depends`.

Finally, you can likely remove `stringr` as a dependency too by working with the base R string manipulation tools.

Overall, removing these packages would make your package have one singular dependency: `data.table`, which would be much nicer for your users.

**Comment by MagicHead99** [comment]
Hi, thanks for the feedback. I'll look into removing the dependencies in a next version. I'm very dependent on tidyverse, but maybe the package doesn't have to.

**Comment by MagicHead99** [comment]
v0.3.1 on github removed dependencies to dplyr and stringr hopefully without breaking anything. I'll submit it to CRAN a bit later.
